# Generated by Django 3.2.4 on 2021-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210623_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img_url_1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='img_url_2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='img_url_3',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='img_url_4',
            field=models.URLField(null=True),
        ),
    ]
