# Generated by Django 3.2.4 on 2021-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='img_url_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='img_url_2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='img_url_3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='img_url_4',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
